// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ZpD7xxqBvnBTQJe4HK0YjUvCo01E6Cs',
    appId: '1:929791059157:web:a2e4542b3833585d96ae5c',
    messagingSenderId: '929791059157',
    projectId: 'test-adecc',
    authDomain: 'test-adecc.firebaseapp.com',
    databaseURL: 'https://test-adecc-default-rtdb.firebaseio.com',
    storageBucket: 'test-adecc.firebasestorage.app',
    measurementId: 'G-L3G0YM7202',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Zpk9utQiQcmaJur4ZcmPpmi308XiroI',
    appId: '1:929791059157:android:9636c12a791ed4d896ae5c',
    messagingSenderId: '929791059157',
    projectId: 'test-adecc',
    databaseURL: 'https://test-adecc-default-rtdb.firebaseio.com',
    storageBucket: 'test-adecc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWvwEF7qAJ1M-z1rI--yyEYscKXlufUW0',
    appId: '1:929791059157:web:fec2c657dc4d0d4696ae5c',
    messagingSenderId: '929791059157',
    projectId: 'test-adecc',
    authDomain: 'test-adecc.firebaseapp.com',
    databaseURL: 'https://test-adecc-default-rtdb.firebaseio.com',
    storageBucket: 'test-adecc.firebasestorage.app',
    measurementId: 'G-SG9EGW1N7N',
  );
}
